import { Injectable, Inject, NotFoundException } from '@nestjs/common'
import type { ProtocolSuggestion } from '@rezeta/shared'
import { ErrorCode } from '@rezeta/shared'
import { PrismaService } from '../../lib/prisma.service.js'
import { ProtocolSuggestionsRepository } from './protocol-suggestions.repository.js'

@Injectable()
export class ProtocolSuggestionsService {
  constructor(
    @Inject(ProtocolSuggestionsRepository) private repo: ProtocolSuggestionsRepository,
    @Inject(PrismaService) private prisma: PrismaService,
  ) {}

  private async assertProtocolExists(protocolId: string, tenantId: string): Promise<void> {
    const protocol = await this.prisma.protocol.findFirst({
      where: { id: protocolId, tenantId, deletedAt: null },
      select: { id: true },
    })
    if (!protocol) {
      throw new NotFoundException({
        code: ErrorCode.PROTOCOL_NOT_FOUND,
        message: 'Protocol not found',
      })
    }
  }

  private async getSuggestionOrThrow(
    protocolId: string,
    suggestionId: string,
    tenantId: string,
  ): Promise<ProtocolSuggestion> {
    const suggestion = await this.repo.findById(suggestionId, tenantId)
    if (!suggestion || suggestion.protocolId !== protocolId) {
      throw new NotFoundException({
        code: ErrorCode.SUGGESTION_NOT_FOUND,
        message: 'Suggestion not found',
      })
    }
    return suggestion
  }

  async list(protocolId: string, tenantId: string): Promise<ProtocolSuggestion[]> {
    await this.assertProtocolExists(protocolId, tenantId)
    return this.repo.listByProtocol(protocolId, tenantId)
  }

  async apply(
    protocolId: string,
    suggestionId: string,
    tenantId: string,
    userId: string,
  ): Promise<ProtocolSuggestion> {
    await this.assertProtocolExists(protocolId, tenantId)
    const suggestion = await this.getSuggestionOrThrow(protocolId, suggestionId, tenantId)

    const currentVersion = await this.prisma.protocolVersion.findUnique({
      where: { id: suggestion.protocolVersionId },
      select: { content: true, versionNumber: true },
    })

    if (currentVersion) {
      const maxVersion = await this.prisma.protocolVersion.aggregate({
        where: { protocolId, tenantId },
        _max: { versionNumber: true },
      })

      const newVersion = await this.prisma.protocolVersion.create({
        data: {
          protocolId,
          tenantId,
          versionNumber: (maxVersion._max.versionNumber ?? 0) + 1,
          content: currentVersion.content as object,
          changeSummary: `Applied suggestion: ${suggestion.impactSummary}`,
          status: 'draft',
          createdBy: userId,
        },
      })

      await this.prisma.protocol.update({
        where: { id: protocolId },
        data: { currentVersionId: newVersion.id },
      })
    }

    return this.repo.markApplied(suggestionId)
  }

  async createVariant(
    protocolId: string,
    suggestionId: string,
    tenantId: string,
    userId: string,
  ): Promise<ProtocolSuggestion> {
    await this.assertProtocolExists(protocolId, tenantId)
    const suggestion = await this.getSuggestionOrThrow(protocolId, suggestionId, tenantId)

    const [originalProtocol, currentVersion] = await Promise.all([
      this.prisma.protocol.findUnique({
        where: { id: protocolId },
        select: { title: true, typeId: true },
      }),
      this.prisma.protocolVersion.findUnique({
        where: { id: suggestion.protocolVersionId },
        select: { content: true },
      }),
    ])

    if (originalProtocol && currentVersion) {
      await this.prisma.$transaction(async (tx) => {
        const variant = await tx.protocol.create({
          data: {
            tenantId,
            typeId: originalProtocol.typeId,
            ownerUserId: userId,
            title: `${originalProtocol.title} - Variante`,
            status: 'draft',
            metadata: {
              autoGenerated: false,
              sourceProtocolId: protocolId,
              suggestionId,
            },
          },
        })

        const version = await tx.protocolVersion.create({
          data: {
            protocolId: variant.id,
            tenantId,
            versionNumber: 1,
            content: currentVersion.content as object,
            changeSummary: `Created from suggestion: ${suggestion.impactSummary}`,
            status: 'draft',
            createdBy: userId,
          },
        })

        await tx.protocol.update({
          where: { id: variant.id },
          data: { currentVersionId: version.id },
        })
      })
    }

    return this.repo.markApplied(suggestionId)
  }

  async dismiss(protocolId: string, suggestionId: string, tenantId: string): Promise<void> {
    await this.assertProtocolExists(protocolId, tenantId)
    await this.getSuggestionOrThrow(protocolId, suggestionId, tenantId)
    await this.repo.markDismissed(suggestionId)
  }
}
