import { Injectable, Logger } from '@nestjs/common'
import nodemailer from 'nodemailer'
import { PrismaService } from '../../lib/prisma.service.js'
import { AuditLogService } from '../../common/audit-log/audit-log.service.js'

interface SuggestionRow {
  id: string
  impactSummary: string
  occurrenceCount: number
  totalUses: number
  occurrencePercentage: { toString(): string }
  protocol: { id: string; title: string }
}

interface VariantRow {
  id: string
  title: string
  metadata: unknown
  createdAt: Date
}

@Injectable()
export class WeeklySummaryService {
  private readonly logger = new Logger(WeeklySummaryService.name)

  constructor(
    private readonly prisma: PrismaService,
    private readonly auditLog: AuditLogService,
  ) {}

  async sendWeeklySummaries(): Promise<void> {
    this.logger.log('Starting weekly summary email job')

    const transporter = this.createTransporter()
    if (!transporter) {
      this.logger.warn('SMTP not configured — skipping weekly summary emails')
      return
    }

    const cutoff = new Date()
    cutoff.setDate(cutoff.getDate() - 7)

    const users = await this.getUsersWithPendingSuggestions()

    let sent = 0
    for (const user of users) {
      try {
        await this.sendSummaryEmail(transporter, user, cutoff)
        sent++
      } catch (err) {
        this.logger.error(`Failed to send summary to ${user.email}: ${String(err)}`)
      }
    }

    this.logger.log(`Weekly summary complete: ${sent}/${users.length} emails sent`)
  }

  private createTransporter(): nodemailer.Transporter | null {
    const host = process.env.SMTP_HOST
    if (!host) return null

    return nodemailer.createTransport({
      host,
      port: Number(process.env.SMTP_PORT ?? '587'),
      secure: process.env.SMTP_SECURE === 'true',
      auth: {
        user: process.env.SMTP_USER ?? '',
        pass: process.env.SMTP_PASS ?? '',
      },
    })
  }

  private async getUsersWithPendingSuggestions(): Promise<
    Array<{ id: string; email: string; fullName: string; tenantId: string }>
  > {
    const suggestions = await this.prisma.protocolSuggestion.findMany({
      where: { status: 'pending' },
      select: {
        protocol: {
          select: {
            creator: { select: { id: true, email: true, fullName: true, tenantId: true } },
          },
        },
      },
      distinct: ['protocolId'],
    })

    const seen = new Set<string>()
    const users: Array<{ id: string; email: string; fullName: string; tenantId: string }> = []

    for (const s of suggestions) {
      const creator = s.protocol.creator
      if (!seen.has(creator.id)) {
        seen.add(creator.id)
        users.push({ ...creator, fullName: creator.fullName ?? creator.email })
      }
    }

    return users
  }

  private async sendSummaryEmail(
    transporter: nodemailer.Transporter,
    user: { id: string; email: string; fullName: string; tenantId: string },
    cutoff: Date,
  ): Promise<void> {
    const [suggestions, newVariants] = await Promise.all([
      this.prisma.protocolSuggestion.findMany({
        where: {
          tenantId: user.tenantId,
          status: 'pending',
          protocol: { creator: { id: user.id } },
        },
        select: {
          id: true,
          impactSummary: true,
          occurrenceCount: true,
          totalUses: true,
          occurrencePercentage: true,
          protocol: { select: { id: true, title: true } },
        },
        orderBy: { occurrencePercentage: 'desc' },
        take: 10,
      }),
      this.prisma.protocol.findMany({
        where: {
          tenantId: user.tenantId,
          createdBy: user.id,
          metadata: { path: ['autoGenerated'], equals: true },
          createdAt: { gte: cutoff },
        },
        select: { id: true, title: true, metadata: true, createdAt: true },
      }),
    ])

    if (suggestions.length === 0 && newVariants.length === 0) return

    const appUrl = process.env.APP_URL ?? 'https://app.rezeta.com'
    const html = this.buildEmailHtml(user.fullName, suggestions, newVariants, appUrl)

    const date = new Date().toLocaleDateString('es-DO', { day: 'numeric', month: 'long' })
    const subject = `Resumen Semanal de Protocolos - ${date}`

    void this.auditLog.record({
      tenantId: user.tenantId,
      actorUserId: user.id,
      actorType: 'cron',
      category: 'communication',
      action: 'email_queued',
      metadata: { recipient: user.email, subject, template: 'weekly_summary' },
      status: 'success',
    })

    const info = (await transporter.sendMail({
      from: process.env.SMTP_FROM ?? 'Rezeta <noreply@rezeta.com>',
      to: user.email,
      subject,
      html,
    })) as { messageId?: string }

    void this.auditLog.record({
      tenantId: user.tenantId,
      actorUserId: user.id,
      actorType: 'cron',
      category: 'communication',
      action: 'email_sent',
      metadata: {
        messageId: info.messageId,
        recipient: user.email,
        subject,
        template: 'weekly_summary',
      },
      status: 'success',
    })
  }

  private buildEmailHtml(
    fullName: string,
    suggestions: SuggestionRow[],
    variants: VariantRow[],
    appUrl: string,
  ): string {
    const firstName = fullName.split(' ')[0] ?? fullName

    const suggestionsHtml =
      suggestions.length > 0
        ? suggestions
            .map(
              (s) => `
        <div style="margin-bottom:20px;padding:16px;border:1px solid #D8D8D2;border-radius:5px;background:#FAFAF7">
          <p style="margin:0 0 4px;font-size:14px;font-weight:600;color:#1C1C1A">
            📋 ${s.protocol.title}
          </p>
          <p style="margin:0 0 12px;font-size:13px;color:#4A4A46">
            💡 ${s.impactSummary}
          </p>
          <p style="margin:0 0 12px;font-size:12px;color:#6B6B66">
            Basado en ${s.occurrenceCount} de tus últimos ${s.totalUses} usos
            (${Math.round(Number(s.occurrencePercentage.toString()))}%)
          </p>
          <div style="display:flex;gap:8px;flex-wrap:wrap">
            <a href="${appUrl}/protocolos/${s.protocol.id}?suggestion=${s.id}&action=apply"
               style="display:inline-block;padding:6px 12px;background:#2D5760;color:white;border-radius:3px;font-size:12px;text-decoration:none">
              Aplicar cambio
            </a>
            <a href="${appUrl}/protocolos/${s.protocol.id}?suggestion=${s.id}&action=variant"
               style="display:inline-block;padding:6px 12px;background:#EAF0F1;color:#1B3A41;border:1px solid #C9D7DA;border-radius:3px;font-size:12px;text-decoration:none">
              Crear variante
            </a>
            <a href="${appUrl}/protocolos/${s.protocol.id}?suggestion=${s.id}&action=dismiss"
               style="display:inline-block;padding:6px 12px;background:#F4F4F0;color:#6B6B66;border:1px solid #D8D8D2;border-radius:3px;font-size:12px;text-decoration:none">
              Ignorar
            </a>
          </div>
        </div>`,
            )
            .join('')
        : ''

    const variantsHtml =
      variants.length > 0
        ? `<h2 style="margin:24px 0 12px;font-size:16px;color:#1C1C1A">Nuevas variantes creadas automáticamente</h2>` +
          variants
            .map(
              (v) => `
        <div style="margin-bottom:12px;padding:12px 16px;border:1px solid #B8CFB2;border-radius:5px;background:#EDF3EC">
          <p style="margin:0;font-size:13px;font-weight:600;color:#2F5C28">✨ ${v.title}</p>
          <a href="${appUrl}/protocolos/${v.id}"
             style="display:inline-block;margin-top:8px;font-size:12px;color:#2D5760;text-decoration:underline">
            Ver protocolo
          </a>
        </div>`,
            )
            .join('')
        : ''

    return `<!DOCTYPE html>
<html lang="es">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#F4F4F0;font-family:'IBM Plex Sans',Arial,sans-serif">
  <div style="max-width:560px;margin:32px auto;background:#FFFFFF;border:1px solid #D8D8D2;border-radius:5px;overflow:hidden">
    <div style="background:#2D5760;padding:20px 24px">
      <p style="margin:0;font-size:18px;font-weight:600;color:#FFFFFF;letter-spacing:-0.01em">Rezeta</p>
    </div>
    <div style="padding:24px">
      <h1 style="margin:0 0 4px;font-size:20px;font-weight:500;color:#1C1C1A">
        Hola, Dr. ${firstName}
      </h1>
      <p style="margin:0 0 20px;font-size:14px;color:#4A4A46">
        Esta semana detectamos oportunidades para optimizar tus protocolos.
      </p>
      ${suggestions.length > 0 ? `<h2 style="margin:0 0 12px;font-size:16px;color:#1C1C1A">Sugerencias pendientes</h2>${suggestionsHtml}` : ''}
      ${variantsHtml}
    </div>
    <div style="padding:16px 24px;border-top:1px solid #EBEBE6;background:#FAFAF7">
      <p style="margin:0;font-size:11px;color:#8E8E88">
        Rezeta · Sistema de gestión médica ·
        <a href="${appUrl}/ajustes/notificaciones" style="color:#6B6B66">Gestionar notificaciones</a>
      </p>
    </div>
  </div>
</body>
</html>`
  }
}
