export const signupStrings = {
  title: 'Crea tu cuenta',
  subtitle: 'Empieza a gestionar tu práctica médica',
  fieldFullName: 'Nombre completo',
  fieldFullNamePlaceholder: 'Dra. María García',
  fieldSpecialty: 'Especialidad',
  fieldSpecialtyPlaceholder: 'Ej. Cardiología, Pediatría',
  fieldEmail: 'Correo electrónico',
  fieldEmailPlaceholder: 'doctor@ejemplo.com',
  fieldPassword: 'Contraseña',
  fieldPasswordPlaceholder: '••••••••',
  fieldPasswordHint: 'Mínimo 8 caracteres con mayúsculas, minúsculas y números',
  fieldConfirmPassword: 'Confirmar contraseña',
  fieldConfirmPasswordPlaceholder: '••••••••',
  submit: 'Crear cuenta',
  submitting: 'Creando cuenta...',
  haveAccount: '¿Ya tienes cuenta?',
  loginLink: 'Inicia sesión',
} as const
