// Staff console is internal Rezeta-staff tooling (not the patient-facing
// product), so its copy is English per the feature spec §7.
export const staffStrings = {
  consoleTitle: 'Rezeta Staff',
  navInstitutions: 'Institutions',
  navPlatformUsers: 'Platform users',
  pageTitle: 'New institution',
  pageSubtitle: 'Create a new institution and its initial super admin.',
  fieldInstitutionName: 'Institution name',
  fieldType: 'Type',
  fieldPlan: 'Plan',
  fieldAdminName: 'Admin name',
  fieldAdminEmail: 'Admin email',
  typeOptions: {
    solo: 'Solo',
    practice: 'Practice',
    clinic: 'Clinic',
    enterprise: 'Enterprise',
  },
  planOptions: {
    free: 'Free',
    solo: 'Solo',
    practice: 'Practice',
    clinic: 'Clinic',
  },
  submit: 'Create institution',
  submitting: 'Creating…',
  error: 'Could not create the institution. Check the details and try again.',
  successTitle: 'Institution created',
  successBody: (email: string): string => `A set-password email was sent to ${email}.`,
} as const

export const platformUsersStrings = {
  pageTitle: 'Platform users',
  pageSubtitle: 'Internal Rezeta staff accounts with access to this console.',
  newUserButton: 'New user',
  tableUser: 'User',
  tableStatus: 'Status',
  tableLastAccess: 'Last access',
  statusActive: 'Active',
  statusInvited: 'Invite pending',
  statusDeactivated: 'Deactivated',
  youChip: 'You',
  resendButton: 'Resend link',
  deactivateButton: 'Deactivate',
  reactivateButton: 'Reactivate',
  neverAccessed: '—',
  formTitle: 'Create platform user',
  nameLabel: 'Full name',
  namePlaceholder: 'Laura Medina',
  emailLabel: 'Email',
  emailPlaceholder: 'laura@rezeta.do',
  linkNote: 'No password is set here — the person receives a set-password link by email.',
  cancelButton: 'Cancel',
  createButton: 'Create user',
  creatingButton: 'Creating…',
  createError: 'Could not create the user. Check the email and try again.',
  actionError: 'The action failed. Try again.',
  loadError: 'Could not load platform users.',
  emptyTitle: 'No platform users yet',
  emptyBody: 'Create the first staff account to get started.',
} as const
