// Staff console is internal Rezeta-staff tooling (not the patient-facing
// product), so its copy is English per the feature spec §7.
export const staffStrings = {
  consoleTitle: 'Rezeta Staff',
  navInstitutions: 'Institutions',
  navSecurity: 'Security',
  navPlatformUsers: 'Platform users',
  navSso: 'SSO connections',
  pageTitle: 'New institution',
  pageSubtitle: 'Create a new institution and its initial super admin.',
  fieldInstitutionName: 'Institution name',
  fieldType: 'Type',
  fieldPlan: 'Plan',
  fieldAdminName: 'Admin name',
  fieldAdminEmail: 'Admin email',
  typeOptions: {
    solo: 'Solo',
    practice: 'Practice',
    clinic: 'Clinic',
    enterprise: 'Enterprise',
  },
  planOptions: {
    free: 'Free',
    solo: 'Solo',
    practice: 'Practice',
    clinic: 'Clinic',
  },
  submit: 'Create institution',
  submitting: 'Creating…',
  error: 'Could not create the institution. Check the details and try again.',
  successTitle: 'Institution created',
  successBody: (email: string): string => `A set-password email was sent to ${email}.`,
  successBackToList: 'Back to institutions',
} as const

export const institutionsStrings = {
  pageTitle: 'Institutions',
  pageSubtitle: 'All institutions on the platform.',
  newButton: 'New institution',
  tableInstitution: 'Institution',
  tablePlan: 'Plan',
  tableUsers: 'Users',
  tableCreated: 'Created',
  usersCell: (active: number, total: number): string => `${active} of ${total}`,
  unnamed: 'Unnamed institution',
  loadError: 'Could not load institutions.',
  emptyTitle: 'No institutions yet',
  emptyBody: 'Create the first institution to get started.',
} as const

export const platformUsersStrings = {
  pageTitle: 'Platform users',
  pageSubtitle: 'Internal Rezeta staff accounts with access to this console.',
  newUserButton: 'New user',
  tableUser: 'User',
  tableStatus: 'Status',
  tableLastAccess: 'Last access',
  statusActive: 'Active',
  statusInvited: 'Invite pending',
  statusDeactivated: 'Deactivated',
  youChip: 'You',
  resendButton: 'Resend link',
  deactivateButton: 'Deactivate',
  reactivateButton: 'Reactivate',
  neverAccessed: '—',
  formTitle: 'Create platform user',
  nameLabel: 'Full name',
  namePlaceholder: 'Laura Medina',
  emailLabel: 'Email',
  emailPlaceholder: 'laura@rezeta.do',
  linkNote: 'No password is set here — the person receives a set-password link by email.',
  cancelButton: 'Cancel',
  createButton: 'Create user',
  creatingButton: 'Creating…',
  createError: 'Could not create the user. Check the email and try again.',
  actionError: 'The action failed. Try again.',
  loadError: 'Could not load platform users.',
  emptyTitle: 'No platform users yet',
  emptyBody: 'Create the first staff account to get started.',
} as const

export const staffSecurityStrings = {
  pageTitle: 'Security',
  pageSubtitle: 'Cross-institution login activity and account health.',
  tileActiveInstitutions: 'Active institutions',
  tileActiveUsers: 'Active users · 30d',
  tileLogins7d: 'Logins · 7d',
  tileDormant: 'Dormant accounts · 60d',
  tileMfaAdoption: 'MFA adoption',
  dormantCallout: (count: number): string => `${count} accounts with no access in 60 days`,
  tableInstitution: 'Institution',
  tablePlan: 'Plan',
  tableMau: 'MAU',
  tableLogins: 'Logins · 14d',
  tableSignals: 'Signals',
  unnamed: 'Unnamed institution',
  signalDormant: (count: number): string => `${count} dormant`,
  signalPending: (count: number): string => `${count} pending invites`,
  loadError: 'Could not load the security overview.',
  emptyTitle: 'No institutions yet',
  emptyBody: 'Institution activity will appear here once accounts start signing in.',
} as const

// Unlike the rest of this staff-console file (English, per feature spec §7),
// the SSO connections page copy is Spanish per the SSO-slice task spec —
// this page is expected to be shown to tenant-side stakeholders, not just
// internal Rezeta staff.
export const ssoStrings = {
  pageTitle: 'Conexiones SSO',
  pageSubtitle: 'Conexiones de inicio de sesión único por institución.',
  newButton: 'Nueva conexión',
  tableInstitution: 'Institución',
  tableName: 'Nombre',
  tableDomains: 'Dominios',
  tableStatus: 'Estado',
  tablePassword: 'Contraseña',
  passwordAllowed: 'Sí',
  passwordBlocked: 'No',
  statusActive: 'Activa',
  statusDisabled: 'Desactivada',
  loadError: 'No se pudieron cargar las conexiones SSO.',
  emptyTitle: 'Aún no hay conexiones SSO',
  emptyBody: 'Crea la primera conexión para habilitar el inicio de sesión único.',
  testButton: 'Probar',
  testingButton: 'Probando…',
  testSuccessTitle: 'Conexión verificada',
  testSuccessChecks: (checks: string[]): string => `Verificado: ${checks.join(', ')}`,
  testFailureTitle: 'La prueba falló',
  editButton: 'Editar',
  deleteButton: 'Eliminar',
  deactivateButton: 'Desactivar',
  activateButton: 'Activar',
  createFormTitle: 'Nueva conexión SSO',
  editFormTitle: 'Editar conexión SSO',
  fieldTenant: 'Institución',
  fieldTenantPlaceholder: 'Selecciona una institución',
  fieldDisplayName: 'Nombre para mostrar',
  fieldDisplayNamePlaceholder: 'Ej. Azure AD',
  fieldIssuerUrl: 'URL del emisor (issuer)',
  fieldIssuerUrlPlaceholder: 'https://login.microsoftonline.com/…',
  fieldClientId: 'Client ID',
  fieldClientIdPlaceholder: 'client_id',
  fieldClientSecret: 'Client secret',
  fieldClientSecretPlaceholder: '••••••••',
  fieldClientSecretEditHelper: 'Dejar vacío para mantener el secreto actual',
  fieldDomains: 'Dominios',
  fieldDomainsPlaceholder: 'clinica.do, hospital.do',
  fieldDomainsHelper: 'Separa varios dominios con comas.',
  fieldAllowPassword: 'Permitir inicio de sesión con contraseña',
  cancelButton: 'Cancelar',
  createButton: 'Crear conexión',
  creatingButton: 'Creando…',
  saveButton: 'Guardar',
  savingButton: 'Guardando…',
  createError: 'No se pudo crear la conexión. Verifica los datos e intenta de nuevo.',
  saveError: 'No se pudo guardar la conexión. Verifica los datos e intenta de nuevo.',
  actionError: 'La acción falló. Intenta de nuevo.',
  confirmDeactivateTitle: 'Desactivar conexión',
  confirmDeactivateBody: (name: string): string =>
    `¿Desactivar la conexión SSO "${name}"? Los usuarios de sus dominios ya no podrán iniciar sesión con SSO.`,
  confirmActivateTitle: 'Activar conexión',
  confirmActivateBody: (name: string): string => `¿Activar la conexión SSO "${name}"?`,
  confirmDeleteTitle: 'Eliminar conexión',
  confirmDeleteBody: (name: string): string =>
    `¿Eliminar la conexión SSO "${name}"? Esta acción no se puede deshacer.`,
} as const
