export const settingsStrings = {
  // ── Auth ─────────────────────────────────────────────────────────────────────
  authSignOut: 'Cerrar sesión',
  authSigningOut: 'Cerrando sesión...',

  // ── Design system ─────────────────────────────────────────────────────────────
  designSystemPrototypeTitle: 'Prototipo de la aplicación',
  designSystemPrototypeDescription: 'Fuente visual de verdad para cada pantalla del MVP',
  designSystemReferenceTitle: 'Referencia de componentes',
  designSystemReferenceDescription: 'Catálogo completo de componentes del sistema de diseño',
} as const

export const templatesStrings = {
  pageTitle: 'Plantillas',
  newButton: 'Nueva plantilla',
  emptyTitle: 'Sin plantillas',
  emptyDescription: 'Crea tu primera plantilla para empezar a diseñar protocolos.',
  listSeeded: 'Predeterminada',
  listLocked: 'Bloqueada',
  listBlockedBy: (count: number) => `Bloqueada por ${count} tipo${count === 1 ? '' : 's'}`,
  listEdit: 'Editar',
  listDelete: 'Eliminar',
  listDeleteConfirm: (name: string) =>
    `¿Eliminar la plantilla "${name}"? Esta acción no se puede deshacer.`,
  loading: 'Cargando plantillas...',
  error: 'No se pudo cargar las plantillas.',
  deleteSuccess: 'Plantilla eliminada.',
  deleteLocked: 'No se puede eliminar: tiene tipos asociados.',
} as const

export const templateEditorStrings = {
  newTitle: 'Nueva plantilla',
  save: 'Guardar plantilla',
  saving: 'Guardando...',
  cancel: 'Cancelar',
  saved: 'Plantilla guardada.',
  unsaved: 'Cambios sin guardar',
  fieldName: 'Nombre de la plantilla',
  fieldNamePlaceholder: 'Ej. Intervención de emergencia',
  fieldSpecialty: 'Especialidad sugerida',
  fieldSpecialtyPlaceholder: 'Ej. cardiología, pediatría',
  statusNew: 'Nueva',
  statusEdited: 'Editada',
  statusLocked: 'Bloqueada',
  lockedBanner:
    'Esta plantilla está bloqueada por uno o más tipos. Elimínalos primero para editarla.',
  lockedTypesPrefix: 'Bloqueada por:',
  addSection: '+ Sección',
  addText: '+ Texto',
  addChecklist: '+ Checklist',
  addSteps: '+ Pasos',
  addDecision: '+ Decisión',
  addDosage: '+ Tabla dosis',
  addAlert: '+ Alerta',
  needsSection: 'Añade primero una sección para contener este bloque.',
  requiredLabel: 'Requerido',
  requiredSectionLabel: 'Requerida',
  deleteSectionConfirm: (title: string, count: number) =>
    `¿Eliminar la sección "${title}" y sus ${count} bloque${count === 1 ? '' : 's'} hijo${count === 1 ? '' : 's'}?`,
  placeholderHint: 'Pista para el médico (opcional)',
  sectionTitleLabel: 'Título de la sección',
  sectionDescLabel: 'Descripción (opcional)',
  navigateAway: 'Tienes cambios sin guardar. ¿Descartar y salir?',
  moveUp: 'Mover arriba',
  moveDown: 'Mover abajo',
  duplicate: 'Duplicar',
  delete: 'Eliminar',
  requiredTooltip: 'Desactiva "Requerido" antes de eliminar.',
  noTitle: '(sin título)',
} as const

export const typesStrings = {
  pageTitle: 'Tipos de protocolo',
  newButton: 'Nuevo tipo',
  emptyTitle: 'Sin tipos de protocolo',
  emptyDescription: 'Crea al menos un tipo para poder crear protocolos.',
  loading: 'Cargando tipos...',
  error: 'No se pudo cargar los tipos.',
  listEdit: 'Renombrar',
  listDelete: 'Eliminar',
  listDeleteConfirm: (name: string) =>
    `¿Eliminar el tipo "${name}"? Esta acción no se puede deshacer.`,
  deleteLocked: 'No se puede eliminar: tiene protocolos asociados.',
  createTitle: 'Nuevo tipo de protocolo',
  createFieldName: 'Nombre',
  createFieldNamePlaceholder: 'Ej. Emergencia, Procedimiento',
  createFieldTemplate: 'Plantilla base',
  createFieldTemplatePlaceholder: 'Selecciona una plantilla',
  createSubmit: 'Crear tipo',
  createSubmitting: 'Creando...',
  createCancel: 'Cancelar',
  renameTitle: 'Renombrar tipo',
  renameField: 'Nombre',
  renameSubmit: 'Guardar',
  renameSubmitting: 'Guardando...',
  renameCancel: 'Cancelar',
  lockedBadge: (count: number) => `Bloqueado · ${count} protocolo${count === 1 ? '' : 's'}`,
  activeBadge: 'Activo',
} as const
